###
POST http://127.0.0.1:8081/api/v1/users

{
"username": "admin",
"password": "123456",
"email": "542255405@qq.com",
"mobile": "18552437190"
}

###
GET http://127.0.0.1:8080/apis/v1/metrics

###
GET http://127.0.0.1:8081/metrics

###
POST http://127.0.0.1:8081/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjIsImV4cCI6MTY1OTY5NDg3MCwiaWF0IjoxNjU5MDkwMDcwLCJpc3MiOiIxMjcuMC4wLjEiLCJzdWIiOiJ1c2VyIHRva2VuIn0.B6GSXtZQUfogCXvUqx6m2U28osuEfvuaZH69gh_LHsk

{
"username": "admin",
"password": "123456",
"email": "542255405@qq.com",
"mobile": "18552437190"
}

###
GET http://127.0.0.1:8081/apis/v1/users?username=jixing12sasa

###
POST http://127.0.0.1:8081/api/v1/login

{
"username": "admin",
"password": "123456"
}

###
POST http://127.0.0.1:8081/api/v1/login

{
"username": "admin",
"password": "123456"
}

###
POST http://127.0.0.1:8081/api/v1/upload
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjIsImV4cCI6MTY1OTY5NDg3MCwiaWF0IjoxNjU5MDkwMDcwLCJpc3MiOiIxMjcuMC4wLjEiLCJzdWIiOiJ1c2VyIHRva2VuIn0.B6GSXtZQUfogCXvUqx6m2U28osuEfvuaZH69gh_LHsk
{
"username": "admin",
"password": "123456"
}

###
POST http://10.50.7.15:8081/apis/v1/login

{
"username": "admin",
"password": "123456"
}

###
GET http://127.0.0.1:8080/get
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjIsImV4cCI6MTY1OTY4MTU0NCwiaWF0IjoxNjU5MDc2NzQ0LCJpc3MiOiIxMjcuMC4wLjEiLCJzdWIiOiJ1c2VyIHRva2VuIn0._PxiZ13qDLI_CK8-wp_QXWchiz_1FOvZ5XL-5mi5NPo

###
GET http://127.0.0.1:8080/set

###
GET http://127.0.0.1:8081/api/v1/get
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjIsImV4cCI6MTY2MDA5NTMzNSwiaWF0IjoxNjU5NDkwNTM1LCJpc3MiOiIxMjcuMC4wLjEiLCJzdWIiOiJ1c2VyIHRva2VuIn0.fQ8IbJBkvu1dphgpJCJ7EEb5vSxOPUib2Nqt-LZypTs

###
GET http://127.0.0.1:8081/api/v1/projectList
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjIsImV4cCI6MTY2MDE5Nzc1NywiaWF0IjoxNjU5NTkyOTU3LCJpc3MiOiIxMjcuMC4wLjEiLCJzdWIiOiJ1c2VyIHRva2VuIn0.vK1m3Oww4FtmL08x-8eW0a1tMxOsbTedsYQTFETBWIA
###
GET http://sbx-newnoa.voneyun.com/govern/project/getProjectDropVo
Authorization: 693ff99503034a37a8efbc75ebc47549
TENANT-ID: 131

GET http://micro-core-web-sbx.voneyun.com/#/micro/adan/servicegovernance/servicemanage

###
GET http://sbx-newnoa.voneyun.com/govern/project/getProjectDropVo
Authorization: e3370bc2ba5149e5acc6a57a2ff5861c
TENANT-ID: 1

###
POST http://sbx-flora.voneyun.com/upms/user/login
Content-Type: application/json;charset=UTF-8

{
"email": "mingyu.ji@sincerecloud.com",
"password": "ckr2fB8UpG15qWTmhxe2aQ=="
}